export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
